### PR TITLE
Removed Google API

### PR DESCRIPTION
**Pull request by Izion**
#59 Removed Google API for Discord Embed

### CODE REVIEW

**Comment by StarlordKK** [comment]
oh nice. does it work without the google api? steam link too?

**Comment by JamieKG** [comment]
by the look of it it uses BitlyApi

**Comment by Izion** [comment]
@StarlordKK Seems to be working okay here, the full url is hidden by the embed you can build the beta branch on my fork to test it out. tsebring may have a reason for not using an embed but with steam blocking both alternatives offered by Google it seems a simple solution.

**Comment by StarlordKK** [comment]
@Izion Thank you so much. Would love to try your beta branch but cant find the exe file. Can u build it for me and release a executable Version? dont know how to get to that exe. i updated my config.json but now…. im lost :)

**Comment by jay7981** [comment]
is there a complied version with the fix somewhere ?

**Comment by JamieKG** [comment]
you would have to download Izion's fork and build it your self im not sure if @tsebring is around anymore

**Comment by jefferson-1** [comment]
Okay so we have multiple contributors wanting to fix stuff and I'd like to add a few fixes of my own. My challenge is I've never been able to build it successfully due to an issue with the config.json.

I'm happy to serve as a maintainer and to get a full Github going if we can get Izion and others to contribute...I'm happy to test and manage the release process and so on.

How can we organize here? I'm over at Knightsgg.com -- look for me on Discord...

**Comment by jefferson-1** [comment]
I snipped this from aliases.json
  [
<<<<<<< beta
      "Rockwell",
      "Rockwell_Character_BP_C"
=======
      "Baby Morallatops",
      "camelsaurus_Character_BP_Child_C"
    ],
    [
      "Baby Basilosaurus",
      "Basilosaurus_Character_BP_Child_C"
>>>>>>> beta
    ],

**Pull request merged**
