### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Lewimaron**
-Added S+ crop plot and generator support.
-Added support for Jamon Stacks
-Added Crystal Isles, The Volcano, and Valguero aliases
-Overhauled vanilla aliases

### CODE REVIEW

**Comment by r2range** [comment]
Lewimaron , could you compile youre version after youre done and share it?

Idea's i would love to see.

- https://i.imgur.com/FXTxPtx.png blank names not sure why but i have those.
- a way to automate adding/removing steamids to a group
- A timer for updating data from the server.

**Comment by JamieKG** [comment]
I believe he has here https://github.com/Lewimaron/ArkBot/releases
but as far as i can tell it dose not have Izion's remove of the google url api

**Comment by jefferson-1** [comment]
Okay so we have multiple contributors wanting to fix stuff and I'd like to add a few fixes of my own. My challenge is I've never been able to build it successfully due to an issue with the config.json.

I'm happy to serve as a maintainer and to get a full Github going if we can get Izion and others to contribute...I'm happy to test and manage the release process and so on.

How can we organize here? I'm over at Knightsgg.com -- look for me on Discord...

**Comment by Lewimaron** [comment]
What sort of config issue are you having?

**Comment by tsebring** [comment]
If you want to maintain this project I'd be happy to switch it over to a separate github account and add you there if that is any help.

**Comment by jefferson-1** [comment]
Re: Config - I think somewhere in the different versions the config format changed. I'm running a build that was downloaded from Tsebring's compile and it works fine. If I try to compile any of the builds, it will complain about the config file format. Even if I remake the entire config, then the web portion won't load. It's a vexing problem.

Re: Maintaining -- I'm happy to help ... To start, I can combine the two recent patches here into one branch and to make builds / post binaries.

**Comment by Lewimaron** [comment]
I can't maintain it, I don't know enough about it to be able to do much more than I already have. I'm happy to submit the stuff I've already done to someone else's version in the future though.

**Comment by Lewimaron** [comment]
Are you compiling the correct build? We had the same issue where whichever version we downloaded it would come out as v1.82 whereas the config format changed in v1.83. In the end I had to fork the whole thing, delete all other branches and then clone the latest files to get the right version.

**Comment by jefferson-1** [comment]
Very odd ... One of the first things that I'd like to do is to move us all up onto a discord or something - it would be easier to collaborate on there than Github comments. Here's a link to the ArkBotDev chan. https://discord.gg/nkGZeT

**Comment by Lewimaron** [comment]
I also joined but can't find it

**Comment by jefferson-1** [comment]
@ark-mod I'm having difficulty with Discord. I'll have to fix it tomorrow morning when I am off the project that I'm on. We'll form up at that time...

**Comment by SirShaw** [comment]
@everyone please DM myself, SirShaw when you get into the discord so I can add you to the dev group. This is why you can not see the channel.

**Comment by SirShaw** [comment]
@ark-mod I have corrected discord and all you have to do is react to the post in the #botdev-role-request channel to see the dev conversations.

**Pull request merged**
